// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/catchain.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Ts                   int64    `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Num                  []byte   `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	Prev                 []byte   `protobuf:"bytes,4,opt,name=prev,proto3" json:"prev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_34eaffa5d3458913, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *Block) GetNum() []byte {
	if m != nil {
		return m.Num
	}
	return nil
}

func (m *Block) GetPrev() []byte {
	if m != nil {
		return m.Prev
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "pb.Block")
}

func init() { proto.RegisterFile("proto/catchain.proto", fileDescriptor_34eaffa5d3458913) }

var fileDescriptor_34eaffa5d3458913 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4e, 0x2c, 0x49, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x03, 0x73, 0x85, 0x98, 0x0a,
	0x92, 0x94, 0x02, 0xb9, 0x58, 0x9d, 0x72, 0xf2, 0x93, 0xb3, 0x85, 0x84, 0xb8, 0x58, 0x32, 0x12,
	0x8b, 0x33, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0xc0, 0x6c, 0x21, 0x3e, 0x2e, 0xa6, 0x92,
	0x62, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0xa6, 0x92, 0x62, 0x21, 0x01, 0x2e, 0xe6, 0xbc,
	0xd2, 0x5c, 0x09, 0x66, 0xb0, 0x12, 0x10, 0x13, 0xa4, 0xab, 0xa0, 0x28, 0xb5, 0x4c, 0x82, 0x05,
	0xa2, 0x0b, 0xc4, 0x4e, 0x62, 0x03, 0x9b, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x98,
	0x0a, 0x09, 0x75, 0x00, 0x00, 0x00,
}
