FROM docker.io/fedora:28

ARG VERSION_DETAILS
ENV VERSION_DETAILS ${VERSION_DETAILS}

ARG PRODUCTION
ENV PRODUCTION ${PRODUCTION}

ENV PHI_UI_ROOT /opt/phi-ui
WORKDIR /opt

COPY ui $PHI_UI_ROOT
COPY config/nginx.conf $PHI_UI_ROOT/config/nginx.conf

RUN dnf update -y && dnf install -y python3 npm nginx && dnf clean all
RUN cd $PHI_UI_ROOT && ln -s $PHI_UI_ROOT/node_modules/@angular/cli/bin/ng /usr/bin && \
  npm install && /usr/bin/ng build $PRODUCTION &&\
  mv dist config /tmp && rm -rf * && mv /tmp/dist /tmp/config .

ENTRYPOINT /usr/sbin/nginx -c config/nginx.conf -p /$PHI_UI_ROOT
