FROM docker.io/fedora:28

ARG VERSION_DETAILS
ENV VERSION_DETAILS ${VERSION_DETAILS}

ARG PRODUCTION
ENV PRODUCTION ${PRODUCTION}

ENV WOODY_UI_ROOT /opt/woody-ui
WORKDIR /opt

COPY ui $WOODY_UI_ROOT
COPY config/nginx.conf $WOODY_UI_ROOT/config/nginx.conf

RUN dnf update -y && dnf install -y python3 npm nginx && dnf clean all
RUN cd $WOODY_UI_ROOT && ln -s $WOODY_UI_ROOT/node_modules/@angular/cli/bin/ng /usr/bin && \
  npm install && npm audit fix && /usr/bin/ng build $PRODUCTION &&\
  mv dist config /tmp && rm -rf * && mv /tmp/dist /tmp/config .

ENTRYPOINT /usr/sbin/nginx -c config/nginx.conf -p /$WOODY_UI_ROOT
