FROM docker.io/centos:7

ENV KAFKA_VERSION 2.1.0
ENV KAFKA_ROOT /opt/kafka

RUN yum upgrade -y && yum update -y && yum install -y \
  vim java-1.8.0-openjdk
RUN curl -s -o /tmp/kafka_2.11-$KAFKA_VERSION.tgz http://apache.mirrors.ionfish.org/kafka/$KAFKA_VERSION/kafka_2.11-$KAFKA_VERSION.tgz && \
  tar xf /tmp/kafka_2.11-$KAFKA_VERSION.tgz -C /opt && ln -s /opt/kafka_2.11-$KAFKA_VERSION $KAFKA_ROOT && \
  rm -f /tmp/kafka_2.11-$KAFKA_VERSION.tgz 

