// Code generated by protoc-gen-go. DO NOT EDIT.
// source: param.proto

package iface_param

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExtractFeatureParams struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtractFeatureParams) Reset()         { *m = ExtractFeatureParams{} }
func (m *ExtractFeatureParams) String() string { return proto.CompactTextString(m) }
func (*ExtractFeatureParams) ProtoMessage()    {}
func (*ExtractFeatureParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{0}
}

func (m *ExtractFeatureParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtractFeatureParams.Unmarshal(m, b)
}
func (m *ExtractFeatureParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtractFeatureParams.Marshal(b, m, deterministic)
}
func (m *ExtractFeatureParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtractFeatureParams.Merge(m, src)
}
func (m *ExtractFeatureParams) XXX_Size() int {
	return xxx_messageInfo_ExtractFeatureParams.Size(m)
}
func (m *ExtractFeatureParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtractFeatureParams.DiscardUnknown(m)
}

var xxx_messageInfo_ExtractFeatureParams proto.InternalMessageInfo

func (m *ExtractFeatureParams) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ExtractFeatureResponse struct {
	Feat                 string   `protobuf:"bytes,1,opt,name=feat,proto3" json:"feat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtractFeatureResponse) Reset()         { *m = ExtractFeatureResponse{} }
func (m *ExtractFeatureResponse) String() string { return proto.CompactTextString(m) }
func (*ExtractFeatureResponse) ProtoMessage()    {}
func (*ExtractFeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{1}
}

func (m *ExtractFeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtractFeatureResponse.Unmarshal(m, b)
}
func (m *ExtractFeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtractFeatureResponse.Marshal(b, m, deterministic)
}
func (m *ExtractFeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtractFeatureResponse.Merge(m, src)
}
func (m *ExtractFeatureResponse) XXX_Size() int {
	return xxx_messageInfo_ExtractFeatureResponse.Size(m)
}
func (m *ExtractFeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtractFeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExtractFeatureResponse proto.InternalMessageInfo

func (m *ExtractFeatureResponse) GetFeat() string {
	if m != nil {
		return m.Feat
	}
	return ""
}

type FacialDetectParams struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FacialDetectParams) Reset()         { *m = FacialDetectParams{} }
func (m *FacialDetectParams) String() string { return proto.CompactTextString(m) }
func (*FacialDetectParams) ProtoMessage()    {}
func (*FacialDetectParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{2}
}

func (m *FacialDetectParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FacialDetectParams.Unmarshal(m, b)
}
func (m *FacialDetectParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FacialDetectParams.Marshal(b, m, deterministic)
}
func (m *FacialDetectParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FacialDetectParams.Merge(m, src)
}
func (m *FacialDetectParams) XXX_Size() int {
	return xxx_messageInfo_FacialDetectParams.Size(m)
}
func (m *FacialDetectParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FacialDetectParams.DiscardUnknown(m)
}

var xxx_messageInfo_FacialDetectParams proto.InternalMessageInfo

func (m *FacialDetectParams) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Point struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{3}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Region struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Region) Reset()         { *m = Region{} }
func (m *Region) String() string { return proto.CompactTextString(m) }
func (*Region) ProtoMessage()    {}
func (*Region) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{4}
}

func (m *Region) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Region.Unmarshal(m, b)
}
func (m *Region) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Region.Marshal(b, m, deterministic)
}
func (m *Region) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Region.Merge(m, src)
}
func (m *Region) XXX_Size() int {
	return xxx_messageInfo_Region.Size(m)
}
func (m *Region) XXX_DiscardUnknown() {
	xxx_messageInfo_Region.DiscardUnknown(m)
}

var xxx_messageInfo_Region proto.InternalMessageInfo

func (m *Region) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Region) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Region) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Region) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Landmark struct {
	Pts                  []*Point `protobuf:"bytes,1,rep,name=pts,proto3" json:"pts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Landmark) Reset()         { *m = Landmark{} }
func (m *Landmark) String() string { return proto.CompactTextString(m) }
func (*Landmark) ProtoMessage()    {}
func (*Landmark) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{5}
}

func (m *Landmark) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Landmark.Unmarshal(m, b)
}
func (m *Landmark) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Landmark.Marshal(b, m, deterministic)
}
func (m *Landmark) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Landmark.Merge(m, src)
}
func (m *Landmark) XXX_Size() int {
	return xxx_messageInfo_Landmark.Size(m)
}
func (m *Landmark) XXX_DiscardUnknown() {
	xxx_messageInfo_Landmark.DiscardUnknown(m)
}

var xxx_messageInfo_Landmark proto.InternalMessageInfo

func (m *Landmark) GetPts() []*Point {
	if m != nil {
		return m.Pts
	}
	return nil
}

type FacialDetectResponse struct {
	Regions              []*Region   `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	Landmarks            []*Landmark `protobuf:"bytes,2,rep,name=landmarks,proto3" json:"landmarks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FacialDetectResponse) Reset()         { *m = FacialDetectResponse{} }
func (m *FacialDetectResponse) String() string { return proto.CompactTextString(m) }
func (*FacialDetectResponse) ProtoMessage()    {}
func (*FacialDetectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{6}
}

func (m *FacialDetectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FacialDetectResponse.Unmarshal(m, b)
}
func (m *FacialDetectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FacialDetectResponse.Marshal(b, m, deterministic)
}
func (m *FacialDetectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FacialDetectResponse.Merge(m, src)
}
func (m *FacialDetectResponse) XXX_Size() int {
	return xxx_messageInfo_FacialDetectResponse.Size(m)
}
func (m *FacialDetectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FacialDetectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FacialDetectResponse proto.InternalMessageInfo

func (m *FacialDetectResponse) GetRegions() []*Region {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *FacialDetectResponse) GetLandmarks() []*Landmark {
	if m != nil {
		return m.Landmarks
	}
	return nil
}

type SimilarityParams struct {
	Feat1                string   `protobuf:"bytes,1,opt,name=feat1,proto3" json:"feat1,omitempty"`
	Feat2                string   `protobuf:"bytes,2,opt,name=feat2,proto3" json:"feat2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimilarityParams) Reset()         { *m = SimilarityParams{} }
func (m *SimilarityParams) String() string { return proto.CompactTextString(m) }
func (*SimilarityParams) ProtoMessage()    {}
func (*SimilarityParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{7}
}

func (m *SimilarityParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimilarityParams.Unmarshal(m, b)
}
func (m *SimilarityParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimilarityParams.Marshal(b, m, deterministic)
}
func (m *SimilarityParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimilarityParams.Merge(m, src)
}
func (m *SimilarityParams) XXX_Size() int {
	return xxx_messageInfo_SimilarityParams.Size(m)
}
func (m *SimilarityParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SimilarityParams.DiscardUnknown(m)
}

var xxx_messageInfo_SimilarityParams proto.InternalMessageInfo

func (m *SimilarityParams) GetFeat1() string {
	if m != nil {
		return m.Feat1
	}
	return ""
}

func (m *SimilarityParams) GetFeat2() string {
	if m != nil {
		return m.Feat2
	}
	return ""
}

type SimilarityResponse struct {
	Score                float32  `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimilarityResponse) Reset()         { *m = SimilarityResponse{} }
func (m *SimilarityResponse) String() string { return proto.CompactTextString(m) }
func (*SimilarityResponse) ProtoMessage()    {}
func (*SimilarityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1747c98d2fc1d5, []int{8}
}

func (m *SimilarityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimilarityResponse.Unmarshal(m, b)
}
func (m *SimilarityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimilarityResponse.Marshal(b, m, deterministic)
}
func (m *SimilarityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimilarityResponse.Merge(m, src)
}
func (m *SimilarityResponse) XXX_Size() int {
	return xxx_messageInfo_SimilarityResponse.Size(m)
}
func (m *SimilarityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimilarityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimilarityResponse proto.InternalMessageInfo

func (m *SimilarityResponse) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*ExtractFeatureParams)(nil), "iface.param.ExtractFeatureParams")
	proto.RegisterType((*ExtractFeatureResponse)(nil), "iface.param.ExtractFeatureResponse")
	proto.RegisterType((*FacialDetectParams)(nil), "iface.param.FacialDetectParams")
	proto.RegisterType((*Point)(nil), "iface.param.Point")
	proto.RegisterType((*Region)(nil), "iface.param.Region")
	proto.RegisterType((*Landmark)(nil), "iface.param.Landmark")
	proto.RegisterType((*FacialDetectResponse)(nil), "iface.param.FacialDetectResponse")
	proto.RegisterType((*SimilarityParams)(nil), "iface.param.SimilarityParams")
	proto.RegisterType((*SimilarityResponse)(nil), "iface.param.SimilarityResponse")
}

func init() { proto.RegisterFile("param.proto", fileDescriptor_1e1747c98d2fc1d5) }

var fileDescriptor_1e1747c98d2fc1d5 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0x9a, 0xa6, 0xdf, 0xd7, 0x2d, 0x12, 0x95, 0x09, 0x55, 0x2e, 0x48, 0x95, 0x41, 0xa8,
	0x42, 0x10, 0x41, 0x7b, 0xe7, 0x50, 0x41, 0x4f, 0x1c, 0x2a, 0xf3, 0x04, 0x26, 0xdd, 0xb6, 0x16,
	0x49, 0x1c, 0xd9, 0x5b, 0xd1, 0xf2, 0xf4, 0x28, 0x4e, 0xd2, 0x9f, 0x03, 0xdc, 0x3c, 0xe3, 0xd9,
	0xf1, 0xec, 0xc8, 0xd0, 0x2b, 0xa4, 0x91, 0x59, 0x5c, 0x18, 0x4d, 0x9a, 0xf5, 0xd4, 0x52, 0x26,
	0x18, 0x3b, 0x8a, 0x8f, 0x20, 0x7c, 0xdd, 0x92, 0x91, 0x09, 0xcd, 0x50, 0xd2, 0xc6, 0xe0, 0xbc,
	0xa4, 0x2d, 0xeb, 0x83, 0xbf, 0x31, 0x69, 0xe4, 0x0d, 0xbd, 0x51, 0x57, 0x94, 0x47, 0x7e, 0x0f,
	0x83, 0x53, 0xa5, 0x40, 0x5b, 0xe8, 0xdc, 0x22, 0x63, 0xd0, 0x5e, 0xa2, 0xa4, 0x5a, 0xec, 0xce,
	0xfc, 0x16, 0xd8, 0x4c, 0x26, 0x4a, 0xa6, 0x2f, 0x48, 0x98, 0xd0, 0xaf, 0xae, 0xd7, 0x10, 0xcc,
	0xb5, 0xca, 0x89, 0x9d, 0x81, 0xb7, 0x75, 0x17, 0x81, 0xf0, 0xb6, 0x25, 0xda, 0x45, 0xad, 0x0a,
	0xed, 0xb8, 0x80, 0x8e, 0xc0, 0x95, 0xd2, 0xf9, 0x5f, 0x2a, 0x16, 0x42, 0xf0, 0xa5, 0x16, 0xb4,
	0x8e, 0x7c, 0xc7, 0x54, 0x80, 0x0d, 0xa0, 0xb3, 0x46, 0xb5, 0x5a, 0x53, 0xd4, 0x76, 0x74, 0x8d,
	0xf8, 0x23, 0xfc, 0x7f, 0x93, 0xf9, 0x22, 0x93, 0xe6, 0x93, 0xdd, 0x80, 0x5f, 0x90, 0x8d, 0xbc,
	0xa1, 0x3f, 0xea, 0x8d, 0x59, 0x7c, 0xd4, 0x4f, 0xec, 0xc2, 0x89, 0xf2, 0x9a, 0x7f, 0x43, 0x78,
	0xbc, 0xd2, 0x7e, 0xfd, 0x07, 0xf8, 0x67, 0x5c, 0xba, 0xc6, 0xe1, 0xe2, 0xc4, 0xa1, 0x4a, 0x2e,
	0x1a, 0x0d, 0x9b, 0x40, 0x37, 0xad, 0x1f, 0xb6, 0x51, 0xcb, 0x0d, 0x5c, 0x9e, 0x0c, 0x34, 0xb1,
	0xc4, 0x41, 0xc7, 0x9f, 0xa1, 0xff, 0xae, 0x32, 0x95, 0x4a, 0xa3, 0x68, 0x57, 0x97, 0x19, 0x42,
	0x50, 0x56, 0xfd, 0x54, 0xd7, 0x59, 0x81, 0x86, 0x1d, 0xbb, 0x5e, 0x6a, 0x76, 0xcc, 0xef, 0x80,
	0x1d, 0xe6, 0xf7, 0xc9, 0x43, 0x08, 0x6c, 0xa2, 0x0d, 0x3a, 0x87, 0x96, 0xa8, 0xc0, 0xf4, 0x0a,
	0xce, 0x13, 0x9d, 0x1d, 0x47, 0x9a, 0x82, 0x7b, 0x12, 0x09, 0x8d, 0xfd, 0xe8, 0xb8, 0x5f, 0x34,
	0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x87, 0xbb, 0x6e, 0x54, 0x02, 0x00, 0x00,
}
